name: Selenium CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Build and Run Tests
        run: mvn clean test